# Configuración específica para perfil Docker
# Este archivo se activa cuando SPRING_PROFILES_ACTIVE=docker

spring:
  datasource:
    url: jdbc:postgresql://db:5432/supportdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    
  # Configuración de logging
  logging:
    level:
      com.uca.parcialfinalncapas: DEBUG
      org.springframework.security: DEBUG
      org.hibernate.SQL: DEBUG

# Configuración JWT
jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTTokenGeneration}
  expiration: ${JWT_EXPIRATION:3600000}

# Configuración del servidor
server:
  port: ${SERVER_PORT:8080} 